RAMPART_PORT_1: 1100
RAMPART_PORT_2: 1200
ARCHIVED_RUNS: 'archived_runs'
RUNS_DIR: 'runs'
RAMPART_IMAGE: 'coreyansley/artifice_polio_rampart'
PIRANHA_IMAGE: 'artifice_piranha'
FONT: 'Arial'
LOGFILE: 'log.txt'
